spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pdksdb
    username: pdks
    password: pdks123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        multiTenancy: SCHEMA

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    baseline-on-migrate: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ilbarsseckin@gmail.com
    password: rrfc lddp egjb jgyx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: cGRrcy1zYWFzLXN1cGVyLXNlY3JldC1rZXktbXVsdGl0ZW5hbnQtMjAyNS1zZWN1cmU=
    expiration: 86400000

  cors:
    allowed-origins:
      -http://10.0.2.154:3000
      - http://localhost:3000

server:
  port: 8080

logging:
  level:
    com.pdks: DEBUG
