name: Deploy Backend
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
           script: |
            cd ~/apps/zecrone-pdks-backend
            git stash
            git pull
            mvn clean package -DskipTests
            pkill -f "pdks-backend-1.0.0" || true
            sleep 2
            setsid nohup java -jar target/pdks-backend-1.0.0.jar > /tmp/backend-pdks.log 2>&1 </dev/null &
            echo "Backend deployed!"